services:
    web:
        build: .
        ports:
            - 3000:3000
            - 5173:5173
        environment:
            - DATABASE_URL=db
        depends_on:
            - db
        restart: always

    db:
        restart: always
        image: mysql
        ports:
            - 3306:3306
        env_file:
            - .env
        volumes:
            - ~/teste:/var/lib/mysql
